import TranslationProvider from "@/providers/TranslationProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <TranslationProvider>
        <body className={inter.className}>{children}</body>
      </TranslationProvider>
    </html>
  );
};

export default RootLayout;
